package cn.cactus.module.system.api.errorcode;

import cn.cactus.module.system.api.errorcode.dto.ErrorCodeAutoGenerateReqDTO;
import cn.cactus.module.system.api.errorcode.dto.ErrorCodeRespDTO;
import cn.cactus.module.system.service.errorcode.ErrorCodeService;
import org.springframework.stereotype.Service;

import javax.annotation.Resource;
import java.time.LocalDateTime;
import java.util.List;

/**
 * Package: cn.cactus.module.system.api.errorcode
 * Description:
 * 错误码 Api 实现类
 *
 * @Author 仙人球⁶ᴳ | 微信：Cactusesli
 * @Date 2023/11/23 16:53
 * @Github https://github.com/lixuanfengs
 */
@Service
public class ErrorCodeApiImpl implements ErrorCodeApi {

    @Resource
    private ErrorCodeService errorCodeService;

    @Override
    public void autoGenerateErrorCodeList(List<ErrorCodeAutoGenerateReqDTO> autoGenerateDTOs) {
        errorCodeService.autoGenerateErrorCodes(autoGenerateDTOs);
    }

    @Override
    public List<ErrorCodeRespDTO> getErrorCodeList(String applicationName, LocalDateTime minUpdateTime) {
        return errorCodeService.getErrorCodeList(applicationName, minUpdateTime);
    }

}