package cn.cactus.module.system.api.errorcode;

import cn.cactus.module.system.api.errorcode.dto.ErrorCodeAutoGenerateReqDTO;
import cn.cactus.module.system.api.errorcode.dto.ErrorCodeRespDTO;

import javax.validation.Valid;
import java.time.LocalDateTime;
import java.util.List;

/**
 * Package: cn.cactus.module.system.api.errorcode
 * Description:
 * 错误码 Api 接口
 *
 * @Author 仙人球⁶ᴳ | 微信：Cactusesli
 * @Date 2023/11/21 15:13
 * @Github https://github.com/lixuanfengs
 */
public interface ErrorCodeApi {

    /**
     * 自动创建错误码
     *
     * @param autoGenerateDTOs 错误码信息
     */
    void autoGenerateErrorCodeList(@Valid List<ErrorCodeAutoGenerateReqDTO> autoGenerateDTOs);

    /**
     * 增量获得错误码数组
     *
     * 如果 minUpdateTime 为空时，则获取所有错误码
     *
     * @param applicationName 应用名
     * @param minUpdateTime 最小更新时间
     * @return 错误码数组
     */
    List<ErrorCodeRespDTO> getErrorCodeList(String applicationName, LocalDateTime minUpdateTime);

}
